---
#title: Luís Fernando Silva Castro de Araújo
#author: Department of Psychiatry, The University of Melbourne
documentclass: article
mainfont: Redacted Script
mainfontoptions:
- Mapping=tex-text
- Scale=1
- Numbers=OldStyle
fontsize: 12pt
lang: pt-BR
geometry: top=1.5cm, bottom=1.5cm, left=1.5cm, right=1.5cm
color-links: yes
#\setlength{\droptitle}{-10em}
#\pretitle{\center\rule{\linewidth}{1pt} \Large\begin{textsc} }
#\posttitle{\end{textsc} \\}
#\preauthor{\begin{large}\begin{center} \begin{emph}}
#\postauthor{\end{emph} \rule{\linewidth}{1pt}\end{center}\end{large}}
header-includes:
  \usepackage{fontawesome}
  \usepackage{sectsty}
  \usepackage{lastpage}
  \usepackage{fancyhdr}
  \usepackage{enumitem}
  \pagestyle{fancy}
  \fancyhf{}
  \renewcommand{\headrulewidth}{0pt}
  \cfoot{\thepage\ of \pageref{LastPage}}
  \allsectionsfont{\scshape}
  \setlist[description]{font={\sffamily}, font={\footnotesize},leftmargin=5em,style=nextline}
output: 
  pdf_document:
    latex_engine: xelatex
---

\begin{minipage}[t]{.50\textwidth}
{\large\bfseries\textsc{My name}}\\
{\small\emph{Clinical Lecturer, The University of Melbourne}}
\end{minipage}
\begin{minipage}[t]{.27\textwidth}
  \flushright \small  \href{mailto:ldearaujo@unimelb.edu.au}{ldearaujo@unimelb.edu.au} \, \faEnvelope \\
  \href{whatsapp:+999999999}{+999999} \, \faWhatsapp\\
  \href{https://github.com/lf-araujo}{lf-araujo} \, \faGithub
\end{minipage}
\begin{minipage}[t]{.23\textwidth}
 \flushright\small Street and number\\ City, \textsc{State}\\  ZIP\\  Country
\end{minipage}

> A short bio goes here.


### Educação
2014-2018 

: [The University of Melbourne, Vic, Australia]{.smallcaps} \newline Doutorado. Project: YYYYYYY. Orientadores: Prof. XXXXX. **Type of scholarship** Funder.

2010-2013 

: [Universidade Estadual de Campinas, UNICAMP, Campinas, Brasil]{.smallcaps} \newline Mestrado. Mestrado em ciências médicas. Projeto: YYYY, Conclusão: 2013. Orientador: Prof. XXXXX.



### Peer-reviewed papers

1. CASTRO-DE-ARAUJO, LFS, Allin M, Picchioni MM, Mcdonald C, Pantelis C, and Kanaan RA. (2018)
“Schizophrenia Moderates the Relationship between White Matter Integrity and Cognition.” Schizophrenia Research. [https://doi.org/10.1016/j.schres.2018.03.033.](https://doi.org/10.1016/j.schres.2018.03.033.)



### Teaching

2018-atual 

: Honorary Clinical Lecturer, The University of Melbourne, Melbourne, Australia.


### Titles

2009 

: Title


### Ad-hoc reviewer to
- Ageing & Mental Health, Dementia & Geriatric Cognitive Disorders

### Other skills
- Estatística com R (lavaan e structural equation modelling).

### Languages
-  Inglês fluente. Francês intermediário.
